### ISSUE TITLE
sample use

### ISSUE THREAD

**Issue by MichaelJohnBradley** [artchen/gatsby-plugin-azure-search#2]
Are you able to provide a sample application that shows how you would use this, or some full code examples.

**Comment by artchen** [comment]
Hi @MichaelJohnBradley , I can look into add an example by pasting how it is used in my personal blog.

**Comment by artchen** [comment]
On a high level, this plugin indexes your site's content into Azure Search, from the custom query that you provide as input to the plugin. This plugin does not include how you would read from the Azure Search to complete the overall searching feature, the reading part will be implemented separately by directly using Azure Search's API. I have a separate repository that contains examples of invoking the APIs of several popular search service, you can check them out here: https://github.com/artchen/universal-search.

**Comment by artchen** [comment]
Added a complete example of `gatsby-config.js` used in one of my gatsby sites. This file is really the only one you need to touch, apart from `package.json`.
